Diet Schedule app/learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views
from django.urls import path

# SET THE NAMESPACE!
app_name = 'basic_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('create/', views.new_schedule,name='create'),
    url('view_diet/', views.view_schedule, name="view_diet"),
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

Diet Schedule app/learning_users/learning_users/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    
    url('view_diet/',include('basic_app.urls')),
    url(r'^$',views.index,name='index'),
    url('special/',views.special,name='special'),
    url('admin/', admin.site.urls),
    url('logout/', views.user_logout, name='logout'),
]

Diet Schedule app/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):

    
    user = models.OneToOneField(User,on_delete=models.CASCADE,)

    
    portfolio_site = models.URLField(blank=True)
    
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        
        return self.user.username

class Schedule(models.Model):

        food_item = models.TextField()
        number_of_times = models.IntegerField()
        duration = models.CharField(max_length=200)

        def __str__(self):
            return self.food_item

Diet Schedule app/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import Schedule
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')


class ScheduleForm(forms.ModelForm):
    class Meta():
        model = Schedule
        fields =('food_item','number_of_times','duration')

Diet Schedule app/learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,ScheduleForm,UserProfileInfoForm
from django.views.generic import TemplateView
from .models import Schedule

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        
        if user_form.is_valid() and profile_form.is_valid():

            
            user = user_form.save()

            
            user.set_password(user.password)

            user.save()


            profile = profile_form.save(commit=False)

            
            profile.user = user

            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    
    return render(request,'basic_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        
        username = request.POST.get('username')
        password = request.POST.get('password')

        
        user = authenticate(username=username, password=password)

        
        if user:
            
            if user.is_active:
                
                login(request,user)
                
                return HttpResponseRedirect(reverse('index'))
            else:
           
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        
        return render(request, 'basic_app/login.html', {})


@login_required
def new_schedule(request):
    
    if request.method =='POST':
        food_item = request.POST.get('food_item')
        number_of_times = request.POST.get('number_of_times')
        duration = request.POST.get('duration')

        t = Schedule(food_item=food_item,number_of_times=number_of_times,duration=duration)
        t.save()

    form = ScheduleForm()
    return render(request,'basic_app/create_schedule.html',{'form':form})
    
@login_required
def view_schedule(request):
    full_schedule=Schedule.objects.all()

    return render(request,'basic_app/view_diet.html',{'Items':full_schedule})

Diet Schedule app/learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link / Admin Link / Register Link#}
          
          
          <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:create' %}">Create new schedule</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:view_diet' %}">View schedule</a></li>

          

          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
          {% endif %}
          
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

Diet Schedule app/learning_users/templates/basic_app/create_schedule.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="container">
        <div class="jumbotron">
            <form method="post">
                {% csrf_token %}
                {{form}}
                <button type="submit" class="save btn btn-default">Submit</button>
            </form>
        </div>
</div>    
{% endblock %}
  

Diet Schedule app/learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Diet Schedule app</h1>
    {% if user.is_authenticated %}
        <h2>Welcome !</h2>
    {% else %}
        <h2></h2>
    {% endif %}
  </div>
</div>

{% endblock %}

Diet Schedule app/learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'basic_app:user_login' %}">
          {% csrf_token %}
          
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password">Password:</label>
          <input type="password" name="password" >

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

Diet Schedule app/learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for signing up!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
         
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

Diet Schedule app/learning_users/templates/basic_app/view_diet.html
{% extends "basic_app/base.html" %}
{% block body_block %}

        {% for food in Items %}
        
        <h2>Food Items:{{food.food_item }}</h2>
        <h2>Number of times to eat in a day:{{food.number_of_times }}</h2>
        <h2>Duration of diet:{{food.duration }}</h2>
        {% endfor %}
          
{% endblock %}