Diet_Schedule/learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# SET THE NAMESPACE!
app_name = 'basic_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url('video/',views.showvideo,name='showvideo'),
    url('viewvideos/',views.viewvideos,name='viewvideos')
]

Diet_Schedule/learning_users/learning_users/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]+static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Diet_Schedule/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User,on_delete=models.CASCADE,)

    # Add any additional attributes you want
    
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

class Video(models.Model):
    name= models.CharField(max_length=500)
    videofile= models.FileField(upload_to='videos/', null=True, verbose_name="")
    created_date = models.DateTimeField(default=timezone.now)
    desciption = models.CharField(max_length=500,default='Action')
    categories = models.CharField(max_length=20,default='Action')
    tags = models.CharField(max_length=10,default='DEFAULT')
    reference_Id = models.CharField(max_length=20,default='DEFAULT')

    def __str__(self):
        return str(self.videofile)

Diet_Schedule/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo,Video

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic',)

class VideoForm(forms.ModelForm):
    class Meta():
        model= Video
        fields= ["name", "videofile", 'desciption','categories', 'tags', 'reference_Id']

Diet_Schedule/learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm



# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Video
from .forms import VideoForm

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'basic_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'basic_app/login.html', {})

@login_required
def showvideo(request):

    lastvideo= Video.objects.last()

    videofile= lastvideo


    form= VideoForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()

    
    context= {'videofile': videofile,
              'form': form
              }
    
      
    return render(request, 'basic_app/videos.html', context)

@login_required
def viewvideos(request):
    
    full_information=Video.objects.all()

    return render(request, 'basic_app/viewvideos.html',{'Items':full_information})

Diet_Schedule/learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:showvideo' %}">Upload Videos</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:viewvideos' %}">Video List</a></li>
          
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
          {% endif %}
          
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

Diet_Schedule/learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Video Uploader</h1>
    {% if user.is_authenticated %}
        <h2>Welcome {{ user.username }}!</h2>
    {% else %}
        <h2>Welcome to the site!</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

Diet_Schedule/learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'basic_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

Diet_Schedule/learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

Diet_Schedule/learning_users/templates/basic_app/videos.html
{% extends "basic_app/base.html" %}
{% block body_block %}

    <nav class="navbar navbar-default">
        <h1>Upload Video!</h1>
        </nav>
<div class="container">
    <div class="jumbotron">
        <form enctype="multipart/form-data" method="POST" action="" >
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Upload" />
        </form>
    </div>
</div>

<video width='400' controls>
<source src='{{ MEDIA_URL }}{{ videofile }}' type='video/mp4'>
Your browser does not support the video tag.
</video>

</p>


<script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpsh'},{'server':'p3plcpnl0769'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script><script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script><script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpsh'},{'server':'p3plcpnl0769'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script><script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'>
</script>
{% endblock %}


Diet_Schedule/learning_users/templates/basic_app/viewvideos.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Content Manager</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">
</head>
<body>
  <nav class="navbar navbar-default">
  <h1>Content Manager</h1>
  </nav>
  <h3>Videos</h3>
  <h3>Categories</h3>
  <h3>Playlists</h3>
  
  
  <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <table id="example"  class="table table-striped table-bordered" >
                <thead>
                    <tr>
                        <th>Thumbnail</th>
                        <th>Name</th> 
                        <th>ID</th>
	                      <th>Created_on</th>
	                      <th>Duration</th>
	                      <th>Plays</th>
                        <th>Status</th>
                        <th>Categories</th>
                    </tr>
                </thead>
                <tbody>
                    {% for details in Items %}
                    <tr>
                        <td></td>
                        <td>{{ details.name }}</td>
                        <td>{{ details.reference_Id }}</td>
                        <td>{{ details.created_date }}</td>
                        <td></td>
                        <td></td>
                        <td>Ready</td>
                        <td>{{ details.categories }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
  </div>
  <script src="//code.jquery.com/jquery-1.12.4.js"></script>
  <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script src="//cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
  <script>
      $(document).ready(function() {
          $('#example').DataTable();
      });
  </script>
</body>
</html>